Import('env')

# pmemkv
pmemkv_include = [ Dir('./pmemkv'),
	Dir('./pmemkv/src'),
	Dir('./pmemkv/src/engines')]
env.Append(LIBPATH=[Dir('./pmemkv')])
env.Append(CPPPATH = pmemkv_include)
PmemKV = env.Make(source = None, target = [File('libpmemkv.so')], MakePath = Dir('./pmemkv'), MakeTargets = "configure sharedlib")
env.Clean(PmemKV, 'pmemkv/bin/libpmemkv.so')

# cpp-btree
env.Append(CPPPATH = [Dir('./cpp-btree-1.0.1')])
