Import('env')

testProgram = env.Program('dragonTest',
            source = [Glob('*.cpp'), Glob('dht/*.cpp')], 
            LIBS=["pthread",
                "boost_program_options",
                "boost_system",
                "boost_filesystem",
                "boost_unit_test_framework",
                "rt",
                "dl",
                "dht",
                File("#/src/3rd/cChord/libmymed.a")
])

test_alias = Alias('test', [testProgram], testProgram[0].path + ' --color_output=yes --log_level=all')

AlwaysBuild(test_alias)