Import('env')

test_sources = [
    Glob('*.cpp'),
    Glob('dht/*.cpp'),
    Glob('store/*.cpp'),
    # Glob('fabric/*.cpp'),
    ]

fogkvTests = env.Program('fogkv_test',
            source = test_sources, 
            LIBS=["pthread",
                "rt",
                "boost_unit_test_framework",
                "dl",
                "boost_program_options",
                "boost_system",
                "boost_filesystem",
                "pmem",
                "pmemobj",
                "pmemkv",
                "fabric",
                "fogkv",
                "mymed"
                ])
env.Install('#bin', [fogkvTests])

logging_option = ' --color_output=yes'
if GetOption('verbose'):
	logging_option += ' --log_level=all'

test_alias = env.Command(['fogkvTests'], "", 'cd %s && ./fogkv_test %s' % (Dir('#bin').abspath, logging_option))
Depends(test_alias, 'install')

AlwaysBuild(test_alias)
