import os

Import('env')

spdk_env = Environment(ENV = os.environ)
spdk_env.Append(CCFLAGS = env['CCFLAGS'])
spdk_env.Append(CXXFLAGS = env['CXXFLAGS'])
spdk_env.Append(CPPFLAGS = env['CPPFLAGS'])
spdk_env.Append(CPPPATH = env['CPPPATH'])
spdk_env.Append(LIBPATH = env['LIBPATH'])
spdk_env.Append(LINKFLAGS = env['LINKFLAGS'])

spdk_libs = [
	'event_bdev',
	'event_copy',
	'event',
	'log',
	'trace',
	'conf',
	'util',
	'bdev',
	'copy',
	'rpc',
	'jsonrpc',
	'json'
];
env.spdk.add_lib(spdk_libs)
env.spdk.env_append(spdk_env);

spdk_app = spdk_env.Program('spdk_example', Glob('*.cpp'))
spdk_env.Depends(spdk_app, '#third-party/spdk')

env.Install('#bin', [spdk_app])
