Import('env')

lib_folders = [
    'db',
    'dht',
    'store',
    'fabric'
    ]
lib_sources = []
for item_dir in lib_folders:
    source_dir = Dir('./%s' % item_dir)
    lib_sources.extend(Glob('%s/*.cpp' % source_dir.abspath))

lib_dependencies = [
    "boost_filesystem",
    "jsoncpp",
    "pmemkv",
    "pmemobj",
    "pmem",
    "fabric",
    "mymed"
    ]

FogKv_shared_lib = env.SharedLibrary('fogkv', [lib_sources], LIBS = lib_dependencies)
FogKv_static_lib = env.StaticLibrary('fogkv', [lib_sources], LIBS = lib_dependencies)
env.Install('#bin', [FogKv_shared_lib])
