Import('env')

env.AppendUnique(LIBPATH=[Dir('.')])
DragonTarget = env.Program('dragon', Glob('*.cpp'), 
            LIBS=["pthread",
                "rt",
                "dht",
                "store",
                File("#third-party/cChord/libmymed.a"),
                "dl",
                "log4cxx",
                "boost_program_options",
                "boost_system",
                "boost_filesystem",
                "boost_thread",
                File("#third-party/pmemkv/bin/libpmemkv.so"),
                File("#third-party/linenoise/liblinenoise.a"),
                ])
