Import('env')

env.AppendUnique(LIBPATH=[Dir('.')])
NodeApp = env.Program('node', Glob('*.cpp'), 
            LIBS=["pthread",
                "rt",
                "dl",
                "log4cxx",
                "boost_program_options",
                "boost_system",
                "boost_filesystem",
                "boost_thread",
                File("#third-party/pmemkv/bin/libpmemkv.so"),
                File("#third-party/linenoise/liblinenoise.a"),
                "mymed",
                "fogkv"
                ])
env.Install('#bin', [NodeApp])