Import('env')

FabricNode = env.Program('fabric_node', Glob('*.cpp'), 
            LIBS=["pthread",
                "boost_program_options",
                "boost_system",
                "boost_filesystem",
                "rt",
                "dl",
                "pthread",
                "mymed",
                File("#third-party/pmemkv/bin/libpmemkv.so"),
                "fogkv"
                ])
env.Install('#bin', [FabricNode])