import os

Import('env')

fabric_env = Environment(ENV = os.environ)
fabric_env.Append(CCFLAGS = env['CCFLAGS'])
fabric_env.Append(CXXFLAGS = env['CXXFLAGS'])
fabric_env.Append(CPPFLAGS = env['CPPFLAGS'])
fabric_env.Append(LIBPATH = env['LIBPATH'])
fabric_env.Append(LINKFLAGS = env['LINKFLAGS'])
fabric_env.Append(CPPPATH = env['CPPPATH'])
fabric_env.Append(RPATH = env['RPATH'])

fokv_includes = [Dir('#include')]

fabric_env.Append(CPPPATH=[fokv_includes])

fabric_libs = ["pthread",
               "boost_program_options",
               "boost_system",
               "boost_filesystem",
               "rt",
               "dl",
               "pthread",
               "mymed",
               "jsoncpp",
               "pmemobj",
               "pmem",
               "pmemkv",
               "fabric",
               "fogkv"
              ]
if 'FOGKV_USE_LOG4CXX' in fabric_env['CPPFLAGS']:
	fabric_libs.append(['log4cxx'])

FabricNode = fabric_env.Program('fabric_node', Glob('*.cpp'), 
            LIBS= fabric_libs)
env.Install('#bin', [FabricNode])
