import os

Import('env')

fabric_env = Environment(ENV = {'PATH' : os.environ['PATH']})
fabric_env.Append(CCFLAGS = env['CCFLAGS'])
fabric_env.Append(CXXFLAGS = env['CXXFLAGS'])
fabric_env.Append(LIBPATH = env['LIBPATH'])
fabric_env.Append(LINKFLAGS = env['LINKFLAGS'])

fokv_includes = [Dir('#include')]

fabric_env.Append(CPPPATH=[fokv_includes])

FabricNode = fabric_env.Program('fabric_node', Glob('*.cpp'), 
            LIBS=["pthread",
                "boost_program_options",
                "boost_system",
                "boost_filesystem",
                "rt",
                "dl",
                "pthread",
                "mymed",
                File("#third-party/pmemkv/bin/libpmemkv.so"),
                "fogkv"
                ])
env.Install('#bin', [FabricNode])
