Import('env')

sources = [Glob('*.cpp'), Glob('workers/*.cpp')]
benchApp = env.Program('bench_node', sources, 
            LIBS=["pthread",
                "log4cxx",
                "boost_program_options",
                "boost_system",
                "boost_filesystem",
                "boost_thread",
                "boost_timer",
                "boost_regex",
                "boost_date_time",
                File("#third-party/pmemkv/bin/libpmemkv.so"),
                File("#third-party/cpu-stat/libcpu-stat.a"),
                File("#third-party/csvpp/libcsvpp.a"),
                "mymed",
                "fogkv"
                ])

env.Install('#bin', [benchApp])