Import('env')

SConscript('#src/3rd/cChord/SConscript', exports='env')
SConscript('dht/SConscript', exports='env')
SConscript('node/SConscript', exports='env')
SConscript('tests/SConscript', exports='env')