Import('env')

SConscript('dht/SConscript', exports='env')
SConscript('store/SConscript', exports='env')
SConscript('fabric/SConscript', exports='env')
SConscript('fabric_node/SConscript', exports='env')
SConscript('node/SConscript', exports='env')
SConscript('tests/SConscript', exports='env')
SConscript('digest/SConscript', exports='env')

SConscript('benchmark/SConscript', exports='env')