Import('env')

SConscript('#src/3rd/SConscript', exports='env')
SConscript('#src/3rd/cChord/SConscript', exports='env')
SConscript('core/SConscript', exports='env')
SConscript('dht/SConscript', exports='env')
SConscript('node/SConscript', exports='env')
SConscript('tests/SConscript', exports='env')
SConscript('digest/SConscript', exports='env')
