Import('env')

env.Program('fabric_node', Glob('*.cpp'), 
            LIBS=["pthread",
                "boost_program_options",
                "boost_system",
                "boost_filesystem",
                "rt",
                "dl",
                "dht",
                "fabricpp",
                "fabric",
                "pthread",
                File("#third-party/cChord/libmymed.a")
                ])
