import os
Import('env')

clinode_env = Environment(ENV = os.environ)
clinode_env.Append(CCFLAGS = env['CCFLAGS'])
clinode_env.Append(CXXFLAGS = env['CXXFLAGS'])
clinode_env.Append(CPPFLAGS = env['CPPFLAGS'])
clinode_env.Append(CPPPATH = env['CPPPATH'])
clinode_env.Append(LIBPATH = env['LIBPATH'])
clinode_env.Append(LINKFLAGS = env['LINKFLAGS'])
clinode_env.Append(CPPPATH = env['CPPPATH'])
clinode_env.Append(RPATH = env['RPATH'])

cchord_includes = [
    Dir('#third-party/cChord/engine/helper'),
    Dir('#third-party/cChord/engine/helper/crypto/'),
    Dir('#third-party/cChord/engine/helper/mongoose_http_server/callbacks'),
    Dir('#third-party/cChord/engine/helper/mongoose_http_server'),
    Dir('#third-party/cChord/engine/helper/thread'),
    Dir('#third-party/cChord/engine/helper/request'),
    Dir('#third-party/cChord/engine/p2p/node'),
    Dir('#third-party/cChord/engine/p2p/protocols'),
    Dir('#third-party/cChord/engine/p2p/protocols/chord'),
    Dir('#third-party/cChord/engine/p2p/transport/http'),
    Dir('#third-party/cChord/engine/p2p/transport')]
pmemkv_includes = [ 
    Dir('#third-party/pmemkv'),
    Dir('#third-party/pmemkv/src'),
    Dir('#third-party/pmemkv/src/engines')
    ]
fokv_includes = [Dir('#include')]
linenoise_includes = [
    Dir('#third-party/linenoise')
    ]

clinode_env.Append(CPPPATH=[cchord_includes, pmemkv_includes, fokv_includes, linenoise_includes])

clinode_libs = ["pthread",
                "rt",
                "dl",
                "boost_program_options",
                "boost_system",
                "boost_filesystem",
                "boost_thread",
                "jsoncpp",
                "mymed",
                "pmem",
                "pmemobj",
                "pmemkv",
                "fabric",
                "fogkv",
                File("#third-party/linenoise/liblinenoise.a"),
              ]
if 'FOGKV_USE_LOG4CXX' in clinode_env['CPPFLAGS']:
	clinode_libs.append(['log4cxx'])

NodeApp = clinode_env.Program('cli_node', Glob('*.cpp'),
            LIBS= clinode_libs)

env.Install('#bin', [NodeApp])
