import os

Import('env')

clinode_env = Environment(ENV = os.environ)
clinode_env.Append(CCFLAGS = env['CCFLAGS'])
clinode_env.Append(CXXFLAGS = env['CXXFLAGS'])
clinode_env.Append(CPPFLAGS = env['CPPFLAGS'])
clinode_env.Append(CPPPATH = env['CPPPATH'])
clinode_env.Append(LIBPATH = env['LIBPATH'])
clinode_env.Append(LINKFLAGS = env['LINKFLAGS'])
clinode_env.Append(RPATH = env['RPATH'])

clinode_libs = ["pthread",
                "rt",
                "dl",
                "boost_system",
                "pmem",
                "pmemobj",
                "pmemkv",
                "fabric",
                "fogkv",
				"mymed"
                ]
if 'FOGKV_USE_LOG4CXX' in clinode_env['CPPFLAGS']:
	clinode_libs.append(['log4cxx'])

fogkv_includes = [Dir('#include')]

clinode_env.Append(CPPPATH=[fogkv_includes])

NodeApp = clinode_env.Program('basic', Glob('*.cpp'),
            LIBS= clinode_libs)

env.Install('#bin', [NodeApp])
